{{ if or (not .Values.handle.existingCertificationSecret) (not .Values.handle.existingAdministrativeSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "handle-net.fullname" . }}
  labels:
    {{- include "handle-net.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.handle.existingCertificationSecret }}{{- if .Values.handle.certificationPassphrase }}
  certification-key-passphrase: {{ .Values.handle.certificationPassphrase | b64enc | quote }}
  {{- end }}{{- end }}
  {{- if not .Values.handle.existingAdministrativeSecret }}{{- if .Values.handle.administrativePassphrase }}
  adm-key-passphrase: {{ .Values.handle.administrativePassphrase | b64enc | quote }}
  {{- end }}{{- end }}
{{ end }}