{{- if and .Values.serviceAccount.create .Values.rbacEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "handle-net.serviceAccountName" . }}
  labels:
{{ include "handle-net.labels" . | nindent 4 }}
{{- end -}}
