apiVersion: v1
kind: Service
metadata:
  name: {{ include "handle-net.name" . }}
  labels:
    {{- include "handle-net.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: clitcp
      protocol: TCP
      name: clitcp
    - port: {{ .Values.service.clientPort }}
      targetPort: cliudp
      protocol: UDP
      name: cliudp
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "handle-net.selectorLabels" . | nindent 4 }}
